addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.14")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
//addSbtPlugin("org.wartremover"    % "sbt-wartremover" % "2.4.10")
